### ISSUE TITLE
Cleaning the include folder in full

### ISSUE THREAD

**Issue by BillyLiggins** [jackdunger/oxsx#55]
While adapting to the new naming conventions, i spent some time finding an error that was ultimately caused by old files from a previous build being in the include folder. 

When running "scon -c" only target files are removed. Looking at the documentation there exist ways of deleting files not in the target list : 
http://scons.org/doc/production/HTML/scons-user.html#idm139837640441408

However its not immediately obvious, to me anyway, where this "Clean" function should go.

**Comment by jackdunger** [comment]
This is a good idea. Scons scripts aren’t executed in the order they are written (it’s voodoo), so the clean function can go just about anywhere. But, for the sake of clarity, I’d put it just after where the header targets are
defined in src/SConscript

**Comment by BillyLiggins** [comment]
#56
